#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a microsoft-edge-dev desktop='^2'
bspc rule -a lightcord desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a spotify desktop='^4'
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a code-oss desktop='^5'

picom -f --experimental-backends &
xsetroot -cursor_name left_ptr
nitrogen --restore &
dunst&
optimus-manager-qt
